### ISSUE TITLE
Extend InvalidOptionException with CommandName

### ISSUE THREAD

**Issue by MarcinIN** [inausoft/netCLI#11]
There should be a way to retrieve command name from `InvalidOptionException`. So that it could be used like:

```cs
...

try
{
    return Executor.RunCLI(config, args, handlers);
}
catch(InvalidOptionException ex)
{
    Console.WritleLine($"Option { ex.OptionName } was not recognized for { ex.CommandName }. Run 'help --command { ex.CommandName }' for detail information.")

}

```

Right now there is no way to determine what command was executed.

**Comment by jmarlew** [comment]
If there are multiple invalid options provided should I expect `AggregateException` which wraps all `InvalidOptionException`?

**Comment by MarcinIN** [comment]
I don't see benefit of it. Can you provide sample usage?

**Comment by jmarlew** [comment]
When calling a command with more than one invalid option, after getting an exception I could fix this one option but get another exception. Validating all options could help me build a valid command right away.

However, we may just assume that people can read and will understand what options are expected for command thanks to `--help` command!

**Comment by matiduck** [comment]
Agreed with @jmarlew  - `AggregateException` seems a good choice for holding bundle of exception, as the same mechism is used for returning exception from Task, where mulitple exception could occur
