### ISSUE TITLE
'-' in the middle of option is working

### ISSUE THREAD

**Issue by MarcinIN** [inausoft/netCLI#35]
**Describe the bug**
Related version: [2.0.0]
Using '--' and '-' to indicates options - works when it is  used in the middle of the name. It should throw an exception.

**To Reproduce**
Steps to reproduce the behaviour:
1. run sampleComman sample--parameter samplevalue

**Expected behaviour**
This should result in an exception.

**Actual behaviour**
This is actually wokrking.

**Comment by jmarlew** [comment]
I will try to paraphrase the requirements: _Option name must not contain hyphens_.
Is this ok? Should we introduce other constraints? 
Maybe it should be defined as: _Option name can only contain alphanumeric characters_. But are numeric chars accepted? If so, can option name start with a numeric character?

**Comment by MarcinIN** [comment]
I guess there is nothing that would prevent you from having hyphen in the middle of an option. You shouldn't on the other hand have an option that will start with one.

This actually will force me to update #36 with what you pointed out - and add constraint on Option naming and command naming as well.
